var dataDemo={
  'sound':{
    "src":"kaola",
    "listPic":[
      {
        "drawable":"anchor",
        "uri":"kaola:top:all",
        "name":"主播"
      },{
        "drawable":"novel",
        "uri":"kaola:audio:category:2109",
        "name":"小说"
      },{
        "drawable":"talkshow",
        "uri":"kaola:audio:category:2119",
        "name":"脱口秀"
      },{
        "drawable":"headlines",
        "uri":"kaola:audio:category:2117",
        "name":"头条"
      },{
        "drawable":"crosstalk",
        "uri":"kaola:audio:category:2082",
        "name":"相声小品"
      },{
        "drawable":"funny",
        "uri":"kaola:audio:category:2086",
        "name":"搞笑"
      }
    ],
    "listMore":[
      {
        "drawable":"anchor",
        "uri":"kaola:audio:category:2166",
        "name":"情感"
      },{
        "drawable":"history",
        "uri":"kaola:audio:category:2179",
        "name":"历史"
      },{
        "drawable":"health",
        "uri":"kaola:audio:category:2130",
        "name":"健康"
      },{
        "drawable":"entertainment",
        "uri":"kaola:audio:category:2182",
        "name":"娱乐"
      },{
        "drawable":"car",
        "uri":"kaola:audio:category:2084",
        "name":"汽车"
      },{
        "drawable":"culture",
        "uri":"kaola:audio:category:2158",
        "name":"军事"
      },{
        "drawable":"education",
        "uri":"kaola:audio:category:2112",
        "name":"教育"
      },{
        "drawable":"finance",
        "uri":"kaola:audio:category:2143",
        "name":"财经"
      },{
        "drawable":"technology",
        "uri":"kaola:audio:category:2148",
        "name":"科技"
      },{
        "drawable":"movie",
        "uri":"kaola:audio:category:2085",
        "name":"影视"
      },{
        "drawable":"campus",
        "uri":"kaola:audio:category:2182",
        "name":"生活"
      },{
        "drawable":"sport",
        "uri":"kaola:audio:category:2174",
        "name":"亲子"
      },{
        "drawable":"open_class",
        "uri":"kaola:audio:category:10152",
        "name":"英语"
      },{
        "drawable":"radio_play",
        "uri":"kaola:audio:category:2151",
        "name":"广播剧"
      }
    ]
  },
  "child":{
    "src":"idaddy",
    "listPic":[
      {
        "drawable":"popular_nursery_rhymes",
        "uri":"idaddy:categories:6707",
        "name":"热门儿歌"
      },{
        "drawable":"fairy_tales",
        "uri":"idaddy:categories:6708",
        "name":"故事"
      },{
        "drawable":"english",
        "uri":"idaddy:categories:7156",
        "name":"英语"
      },{
        "drawable":"chinese",
        "uri":"idaddy:categories:7716",
        "name":"国学"
      }
    ],
    "listMore":[
      {
        "drawable":"encyclopedias",
        "uri":"idaddy:categories:6948",
        "name":"音乐"
      },
      {
        "drawable":"books",
        "uri":"idaddy:categories:12724",
        "name":"广播剧"
      },
      {
        "drawable":"cartoon",
        "uri":"idaddy:categories:16815",
        "name":"科普"
      },
      {
        "drawable":"education",
        "uri":"idaddy:categories:17164",
        "name":"名著"
      },
      {
        "drawable":"anchor",
        "uri":"idaddy:categories:17174",
        "name":"宝贝秀"
      },
      {
        "drawable":"ducation",
        "uri":"idaddy:categories:17176",
        "name":"胎教"
      },
      {
        "drawable":"oxford",
        "uri":"idaddy:categories:17466",
        "name":"绘本"
      },
      {
        "drawable":"chinese_forgein",
        "uri":"idaddy:categories:19205",
        "name":"历史"
      },
      
    ]
  }
}
exports.getData = function(method,data){
  var backData={
      "code":'100',
      "jsonrpc": "2.0",
      "data":dataDemo
  }
  if(method=='DELETE'){
      backData={
          "code":'999',
          "msg":"不支持DELETE方法"
      }
  }
  return JSON.stringify(backData);
}